version: '3.5'
services:
    minio1:
        image: minio/minio
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_node1
        # ports:
        #     - 9000:9000
        expose:
        - ${BACKEND_PORT}
        environment:
            MINIO_ACCESS_KEY: ${ACCESS_KEY}
            MINIO_SECRET_KEY: ${SECRET_KEY}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
        volumes:
            - disk1:/data1
        command: server /data1
        networks:
            - minio_net

    nginx:
        image: nginx
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        depends_on:
        - minio1
        # ports:
        # - 80:80
        expose:
        - ${NGINX_PORT}
        volumes:
        - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
        environment:
        - VIRTUAL_ROOT=/var/www/html
        - LETSENCRYPT_HOST=${SERVER_NAME}.${DOMAIN_NAME}
        - VIRTUAL_HOST=${SERVER_NAME}.${DOMAIN_NAME}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        - BACKEND_NAME=${COMPOSE_PROJECT_NAME}_node1:${BACKEND_PORT}
        command: /bin/bash -c "envsubst '$$VIRTUAL_ROOT $$BACKEND_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
        networks:
        - minio_net
        - webproxy

networks:
    minio_net:
        name: minio
    webproxy:
        external:
            name: ${WEBPROXY_NETWORK}

volumes:
  disk1:
    external: true
