version: '3.5'
services:
    nginx:
        image: nginx:latest
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./cache:/var/cache/nginx/minio_cache
            - ./logs:/var/log/nginx
        networks:
            - minio_net

    minio1:
        image: minio/minio
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_node1
        environment:
            MINIO_ACCESS_KEY: ${ACCESS_KEY}
            MINIO_SECRET_KEY: ${SECRET_KEY}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
        volumes:
            - disk1:/disk1/node1
            - disk2:/disk2/node1
            - disk3:/disk3/node1
            - disk4:/disk4/node1
        command: server /disk1/node1 /disk2/node1 /disk3/node1 /disk4/node1
        networks:
            - minio_net

    minio2:
        image: minio/minio
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_node2
        environment:
            MINIO_ACCESS_KEY: ${ACCESS_KEY}
            MINIO_SECRET_KEY: ${SECRET_KEY}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
        volumes:
            - disk1:/disk1/node3
            - disk2:/disk2/node3
            - disk3:/disk3/node3
            - disk4:/disk4/node3
        command: server /disk1/node3 /disk2/node3 /disk3/node3 /disk4/node3
        networks:
            - minio_net

    minio3:
        image: minio/minio
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}_node3
        environment:
            MINIO_ACCESS_KEY: ${ACCESS_KEY}
            MINIO_SECRET_KEY: ${SECRET_KEY}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
        volumes:
            - disk1:/disk1/node4
            - disk2:/disk2/node4
            - disk3:/disk3/node4
            - disk4:/disk4/node4
        command: server /disk1/node4 /disk2/node4 /disk3/node4 /disk4/node4
        networks:
            - minio_net


networks:
    minio_net:
        name: minio

volumes:
  disk1:
  disk2:
  disk3:
  disk4:
